### ISSUE TITLE
How to add multiple events in the component?          

### ISSUE THREAD

**Issue by dollyshah-02-zz** [angeloashmore/immutable-ics#7]

**Comment by dollyshah-02-zz** [comment]
My code: 
```js
 const calendar = new Component({
            name: 'VCALENDAR',
            properties: [
                new Property({ name: 'VERSION', value: 2 })
            ],
            components: [
                json.map(ele => {
                    const component = new Component({
                        name: 'VEVENT',
                        properties: [
                            new Property({
                                name: 'DTSTART',
                                value: new Date(ele.start_date)
                            }),
                            new Property({
                                name: 'DTEND',
                                value: new Date(ele.end_date)
                            }),
                            new Property({
                                name: 'UID',
                                value: ele.title
                            }),
                            new Property({
                                name: 'LOCATION',
                                value: ele.location
                            }),
                            new Property({
                                name: 'SUMMARY',
                                value: ele.notes
                            })
                        ]
                    });
                })
            ]

        })
```

**Comment by angeloashmore** [comment]
@dollyshah-02 You can push components, such as `VEVENT`, on existing components, such as `VCALENDAR`, using `pushComponent`.

```js
const calendar = // The same calendar you defined above

const event = new Component({
  name: 'VEVENT',
  properties: [
    new Property({
      name: 'DTSTART',
      parameters: { VALUE: 'DATE' },
      value: new Date('1991-07-11 7:00:00')
    })
  ]
})

// Add the new event to the existing calendar component.
calendar.pushComponent(event)
```

**Comment by angeloashmore** [comment]
@dollyshah-02 In your code above, your `map` function is not returning the component you created.

```js
json.map(ele => {
  const component = new Component({
    // ...
  })

  return component
})
```

Without returning `component` at the end of your `map` function, the function returns undefined. That's probably why you're seeing no components added to your `VCALENDAR`.

**Comment by RameshBacancy** [comment]
> @dollyshah-02 In your code above, your `map` function is not returning the component you created.
> 
> ```js
> json.map(ele => {
>   const component = new Component({
>     // ...
>   })
> 
>   return component
> })
> ```
> 
> Without returning `component` at the end of your `map` function, the function returns undefined. That's probably why you're seeing no components added to your `VCALENDAR`.

but , using pushcomponent method, i might not be able to add VEVENTs according to the json data i am getting. using pushcomponent, i can add static components only ,i cannot loop on my data

**Comment by angeloashmore** [comment]
@RameshBacancy your application code will need to handle that. This library provides functionality to add events on creation as well as to add events as needed. Your app will need to loop over your JSON, determine if it needs to add an event, and call `pushComponent` as necessary.

Note that all functions are immutable so you will need to reassign `calendar` each time you call `pushComponent`.
